server:
  port: ${port:8181}
  error:
    include-message: always
spring:
  rabbitmq:
    host: clam-01.rmq.cloudamqp.com
    username: uymxsaau
    password: jhEo4pivjk7sdKzlx4JKWTOe6G650RxP
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fiapAgro?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#  mail:
#    host: email-ssl.com.br
#    port: 465
#    username: send@lucasgoiana.com
#    password: Fiap@@2021
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            enable: false
#    test-connection: true
  mail:
    host: email-ssl.com.br
    port: 465
    username: send@lucasgoiana.com
    password: a@1235222aA
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    test-connection: true

